name: tp3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:   
    sdk: flutter   
  # TP2 Requirements
  provider: ^6.0.5          # For Exercise 1 Q1
  flutter_bloc: ^8.1.3      # For Exercise 1 Q2
  equatable: ^2.0.5         # Helper for BLoC
  http: ^1.1.0              # For Exercise 2 (Weather API)
  intl: ^0.20.0              # For Date Formatting
  font_awesome_flutter: ^10.6.0 # For Weather Icons

  firebase_core: 
  firebase_auth:
  cloud_firestore: 
  firebase_storage: 
  
  # Tools for Ex 3
  image_picker: ^1.0.4
  audioplayers: ^5.2.1
  
  # Default
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
